### ISSUE TITLE
Running rcli first backup fails with: no such file or directory

### ISSUE THREAD

**Issue by dohnto** [mhausenblas/reshifter#2]
Hello, I follow the the README from master branch 057547d on kubernetes master:

```bash
$ kubectl  version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-11T07:11:31Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-11T07:11:31Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

```bash
$ etcdctl --version
etcdctl version: 3.1.7
API version: 2
```

```bash
$ ./rcli-linux version
0.3.9
```

```bash
$ ./rcli-linux explore
Exploring etcd endpoint http://127.0.0.1:2379
Version: 3.1.7
Secure: insecure etcd, no SSL/TLS configured
Distro: OpenShift
```

**Q1**: `Distro: Openshift` seems kind of missleading... it this tool supported for bare Kubernetes without Openshift?

```bash
$ ./rcli-linux stats
Collecting stats from etcd endpoint http://127.0.0.1:2379
Vanilla Kubernetes [keys:0, size:0]
```

```bash
$ ./rcli-linux backup create 
ERRO[0000] Can't create archive or no content to back up: lstat /tmp/reshifter/1500020159: no such file or directory 
$ ls -l /tmp/reshifter/* 
-rw-r--r-- 1 root root 0 Jul 14 10:15 /tmp/reshifter/1500020159.zip
``` 

**Q2**: Why is the initial backup failing?

Thank you

**Comment by mhausenblas** [comment]
Thanks a lot for giving ReShifter a try, much appreciated @dohnto! 

re **Q1**: yes, it supports all sorts of Kubernetes distros incl. but not limited to OpenShift. Since `stats` gives you a different answer than `explore` I believe this is a bug, so I'll investigate it. If you could share a few more details about your Kubernetes setup pls, that would help me trying to recreate the issue.

re **Q2**: this error message suggests that there's nothing in etcd that ReShifter recognizes to back up. Given your first error message I assume this is a K8S distro such as Tectonic which I haven't tested against, so again, if you could provide more details about your setup, I can help more effectively.

**Comment by dohnto** [comment]
We run just Kubernetes on bare metal without any fancy provider, we use our custom SaltStack states to deploy the kubernetes but it is just build binaries from github.com and packed into debian packages. Not sure what more information do you need. I can provide some content of etcd if needed.

**Comment by mhausenblas** [comment]
OK @dohnto that is already super useful, thank you! Can you maybe do me a favour and share the output of `etcdctl ls / --recursive`? My hunch is that ReShifter gets confused since you seem to run an etcd3 in API v2 mode. Certainly something on my side, but I need to better understand what keys you're having in there, please.

**Comment by dohnto** [comment]
```
$ etcdctl  --ca-file=ca.pem  --key-file=key.pem  --cert-file=cert.pem ls / --recursive
2017-07-14 20:14:51.482701 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
/coreos.com
/coreos.com/network
/coreos.com/network/config
/coreos.com/network/subnets
/coreos.com/network/subnets/172.24.23.0-24
/coreos.com/network/subnets/172.24.16.0-24
/coreos.com/network/subnets/172.24.1.0-24
/coreos.com/network/subnets/172.24.81.0-24
/coreos.com/network/subnets/172.24.51.0-24
/coreos.com/network/subnets/172.24.0.0-24
/coreos.com/network/subnets/172.24.40.0-24
/coreos.com/network/subnets/172.24.97.0-24
/coreos.com/network/subnets/172.24.37.0-24
/coreos.com/network/subnets/172.24.11.0-24
```

But
```
```

**Comment by mhausenblas** [comment]
Yes, that explains it @dohnto! Now, in the first case you're using the v2 API and it suggests that you're actually not using vanilla Kubernetes but Tectonic. Can you confirm this please? In the second case you're using the v3 API and this (`/registry`) is what makes ReShifter think it's vanilla Kubernetes. Now I understand one part but I still don't have enough information to try to re-create the setup. Alternatively, it could be that this etcd is also used for something else. Same applies here, I don't have enough insights into the overall setup to judge it.

**Comment by dohnto** [comment]
No, we are using vanilla Kubernetes. We also use flannel which stores some data to etcd (the `/coreos` prefix). We migrated from Kubernetes 1.5 and etcd v2 to Kubernetes 1.6 and etcd v3, but flannel cannot comunicate with etcd using v3 api and therefore there are some data still left. But all kubernetes related data are stored now (after migration) in v3 storage.

**Comment by mhausenblas** [comment]
Brilliant, thanks a lot for clarifying this! I'll whip up some test cases and try to reproduce this tomorrow at the GopherCon community (hacking) day. Will keep you up to date how it goes @dohnto :)

**Comment by mhausenblas** [comment]
Hey @dohnto can you do me a favour and try out the [v0.3.10](https://github.com/mhausenblas/reshifter/releases/tag/v0.3.10-alpha) release I just pushed? Should fix it. Fingers crossed ;)

**Comment by eremid** [comment]
Hello,

Same problem here with 0.3.10-alpha. Like @dohnto,  I migrated from Kubernetes 1.5 and etcd v2 to Kubernetes 1.6 and etcd v3 and now to Kubernetes 1.7.

`/ # etcdctl --version
etcdctl version: 3.0.17
API version: 2
`

```
$ ./rcli-linux  explore
Exploring etcd endpoint http://127.0.0.1:2379
Version: 3.0.17
Secure: insecure etcd, no SSL/TLS configured
Distro: Vanilla Kubernetes

$ ./rcli-linux  stats
Collecting stats from etcd endpoint http://127.0.0.1:2379
Vanilla Kubernetes [keys:0, size:0]
```

Thanks you

**Comment by mhausenblas** [comment]
OK, thanks @eremid! What does `etcdctl ls / --recursive`  and `ETCDCTL_API=3 etcdctl ls / --recursive` give for you?

**Comment by eremid** [comment]
```
/ # etcdctl ls / --recursive
/github
[...]
```
^-- my stuff

`ls` is not avalaible for the APIv3
```
/ # ETCDCTL_API=3 etcdctl ls / --recursive
Error: unknown command "ls" for "etcdctl"
Run 'etcdctl --help' for usage.
Error:  unknown command "ls" for "etcdctl"
```

but :

```
/ # ETCDCTL_API=3 etcdctl get / --keys-only --prefix                     
/registry/apiregistration.k8s.io/apiservices/v1.                
/registry/apiregistration.k8s.io/apiservices/v1.authentication.k8s.io
/registry/apiregistration.k8s.io/apiservices/v1.authorization.k8s.io
/registry/apiregistration.k8s.io/apiservices/v1.autoscaling   
/registry/apiregistration.k8s.io/apiservices/v1.batch         
```

Thanks

**Comment by dohnto** [comment]
```
$ ./rcli-linux version
0.3.10
$ ./rcli-linux explore
Exploring etcd endpoint http://127.0.0.1:2379
Version: 3.1.7
Secure: insecure etcd, no SSL/TLS configured
Distro: Vanilla Kubernetes
$ ./rcli-linux backup create
ERRO[0000] Can't create archive or no content to back up: lstat /tmp/reshifter/1500280298: no such file or directory 
```

**Comment by mhausenblas** [comment]
@eremid doh, sorry re the `ls` with v3, ofc it's `get` ;) … and thank you!

@dohnto ack and thanks!

Folks, thanks a lot for being patient here with me. Just returned from Denver and looking into it. I think I know what it is (pattern I see here is v2/v3 with etcd being used for both K8S and something else as well). I'll put together a few more test cases and *will* figure this out. Please do allow me some proper investigation, I'll follow up ASAP, once I've found this bug and fixed it (for good, I hope, this time).

**Comment by mhausenblas** [comment]
OK @dohnto and @eremid I've just cut [v0.3.12](https://github.com/mhausenblas/reshifter/releases/tag/v0.3.12-alpha) and hope this release addresses your issues, can you please give it a try?

**Comment by dohnto** [comment]
Ok now it works (does not fail), but the archine only contains single file:
```
1500384883/registry/ThirdPartyResourceData/stable.example.com/crontabs/tomas-dohnalek/my-new-cron-object/content
```

Nothing more.

**Comment by mhausenblas** [comment]
Ha, strange @dohnto … I mean, great that it doesn't fail anymore but curious how comes that it apparently only archives one key. Sounds like a couple of more test cases for me. Sorry, again, for the unsatisfying outcome ATM and I hope you can wait until I've fixed it, I'm on it …

**Comment by eremid** [comment]
Same problem : juste a signle file :
```
$ unzip /tmp/reshifter/1500389058.zip
Archive:  /tmp/reshifter/1500389058.zip
  inflating: 1500389058/registry/apiregistration.k8s.io/apiservices/v1./content
```

And :

```
$ ./rcli-linux.1 stats                                                   
Collecting stats from etcd endpoint http://127.0.0.1:2379               
Vanilla Kubernetes [keys:1, size:587]    
```

**Comment by mhausenblas** [comment]
Yeah, well, it was a combination of logical bug and simple stupidity on my end. Passing the relevant test cases now and the [v0.3.13](https://github.com/mhausenblas/reshifter/releases/tag/v0.3.13-alpha) release *should* address it. I sincerely hope so! 

@dohnto and @eremid can you please give it a try?

**Comment by dohnto** [comment]
The issue is still remaining, only third part resources are backuped.

**Comment by eremid** [comment]
Same here !

**Comment by mhausenblas** [comment]
This is strange @dohnto … it passes the relevant test cases and I also tried manually some other things via `rcli backup` (etcd3 with v2 API). I did discover a bug now in `stats` but the backup command works for me. I might be overlooking something where we differ but I'm not sure I see it 8-/

**Comment by mhausenblas** [comment]
Right, since both of you seem still to experience the same issue, I need to figure out what I am doing wrong. Fixing the stats bug now and will re-visit your issue right afterwards. Maybe this triggers a new idea …

**Comment by mhausenblas** [comment]
@eremid @dohnto sorry for the delay here and can you please use [v0.3.15-alpha](https://github.com/mhausenblas/reshifter/releases/tag/v0.3.15-alpha) to check if you're still experiencing the issues above?

**Comment by eremid** [comment]
\o/
It's ok ! Thanks

**Comment by mhausenblas** [comment]
OK @eremid thanks for confirming it! Waiting for @dohnto and then (maybe) close this one off ;)

**Comment by eremid** [comment]
I've just migrate my k8s etcd keys from a standalone etcd to a 3 etcd nodes with rcli backup ;-)

**Comment by dohnto** [comment]
Fixed for me. Thank you.

**Comment by mhausenblas** [comment]
\o/

Again, thank you both @dohnto and @eremid and very happy being able to close this one, learned a lot here ;)

**Comment by eremid** [comment]
There remains a small problem : keys in v2 api format are restored in v3 :(

**Comment by mhausenblas** [comment]
Sounds more like a big problem @eremid but I'd really prefer if you could create a separate issue for it, if that's OK for you?

**Comment by eremid** [comment]
Ok
